services:
  - type: web
    name: wordtopdf
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y pandoc
      pip install -r requirements.txt
    startCommand: gunicorn app:app
